<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>UserByID</title>
</head>
<body>

<p>${user.id}, ${user.name}, ${user.login}, ${user.age}, ${user.gender}, ${pulse}</p>
</body>
</html>